name: build

on:
  pull_request:
  push:
    branches: [ master, develop ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Register NDK
        run: "echo 'ndk.path=${{ steps.setup-ndk.outputs.ndk-path }}' >> local.properties"

      - name: Assemble Android Test 
        run: ./gradlew assembleAndroidTest --stacktrace

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck --stacktrace

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          files: "tehreer-android/build/reports/coverage/androidTest/debug/report.xml"
          verbose: true
