name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.2.6472646" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Register NDK
        run: "echo 'ndk.path=/usr/local/lib/android/sdk/ndk/21.2.6472646/' >> local.properties"

      - name: Run Tests
        run: ./gradlew connectedAndroidTest --stacktrace
